name: mealsafe
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  camera_android: ^0.10.10+1
  camera: ^0.11.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  realm: ^20.0.1
  uuid: ^4.0.1
  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_tesseract_ocr: ^0.4.28




dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata/
    - assets/

